### ISSUE TITLE
Possible issue in dereferencing link.operationRef

### ISSUE THREAD

**Issue by frantuma** [swagger-api/apidom#1483]
ApiDOM dereferencer is currently also dereferencing Link `operationRef` fields resulting in a `operation` field as sibling to `operationRef`, see e.g. [this test](https://github.com/swagger-api/apidom/blob/0688c2519c5773239e485b448294f28f141ae6ef/packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/operation-ref-external/dereferenced.json#L7-L10=).

This doesn't seem correct as there is no `operation` field in `Link`.

**Comment by char0n** [comment]
Discussed with @frantuma that instead of adding artificial `operation` field during dereference, we'll put the resolved `Operation Object` in meta of the referencing field, either `operationRef` or `operationId`.
