### ISSUE TITLE
ls: oas3.1 documentation for media-type

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#1990]

**Comment by tim-lai** [comment]
@frantuma Just wanted to confirm that we do not need to provide "extended" documentation for Media Type Object. 
e.g. these three lengthy topics:

- [Considerations for File Uploads](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#considerations-for-file-uploads)

- [Support for x-www-form-urlencoded Request Bodies](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#support-for-x-www-form-urlencoded-request-bodies)

- [Special Considerations for multipart Content
](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#special-considerations-for-multipart-content)

docs: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#mediaTypeObject
initial implementation PR: https://github.com/swagger-api/apidom/pull/2040

**Comment by frantuma** [comment]
@tim-lai similarly to #2024 would just add a link to these topics

**Comment by tim-lai** [comment]
Thanks. Followup PR with recommendations: #2048
