### ISSUE TITLE
ls: oas3.1 documentation for header

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#1992]

**Comment by tim-lai** [comment]
@frantuma How do you want to handle the docs for the `Header Object`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#header-object)? It basically says to follow the [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameterObject) minus some changes. However the `Parameter Object` has a long list of examples, self-references, and links. Do we want to directly adapt the docs from `Parameter Object` to `Header Object` as much as possible? e.g. there likely will not be corresponding documentation links.

**Comment by tim-lai** [comment]
per conversation with @char0n , will implement existing documenation as-is, with no additional modifications. Expect users who need more information on the `parameter` object to follow the link provided.

**Comment by char0n** [comment]
I did some additional analysis and produced https://github.com/swagger-api/apidom/pull/2008, which adds the fields documentations with customized documentation that only applies in `header` context.
