### ISSUE TITLE
ls: oas3.1 documentation for xml

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#2024]

**Comment by tim-lai** [comment]
@frantuma Do we want to include ALL of the documentation examples for this Object? It's very lengthy.

[XML Object Examples](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#xml-object-examples)

- [No XML Element](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#no-xml-element)
- [XML Name Replacement](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#xml-name-replacement)
- [XML Attribute, Prefix and Namespace](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#xml-attribute-prefix-and-namespace)
- [XML Arrays](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#xml-arrays). This one in particular has many "sub" examples

**Comment by frantuma** [comment]
@tim-lai would append a link to example section in specification at the end of docs
@char0n any comment/thought?

**Comment by char0n** [comment]
My overall recommendation to this would be to use it as it is. The monaco documentation tooltip has enough space to render it properly and has a scroll-able support.
We may decide differently in future, but for now it make sense to show all the examples as the author of the spec thought they were necessary to put them there.

**Comment by tim-lai** [comment]
Implemented. snippet from PR #2049:

> Also add custom section for `Additional documentation topics` that provide external links for further reading.
