### ISSUE TITLE
documentation: which method for character encoding for pipe `|`

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#2039]
@char0n , cc: @frantuma 
moving from closed PR comment: https://github.com/swagger-api/apidom/pull/2038 to this ticket.

> I just noticed something with the transform-spec-fragment.js... Using a copy/paste from the raw content, there exists a \|, e.g. [Header Object](#headerObject) \| [Reference Object](#referenceObject)], which gets transformed to \\|. This is fine, and renders as expected in Monaco.
> 
> However, there's also usage of &#124; as the html separator for |. e.g. [Header Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#headerObject) &#124; [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#referenceObject)].
> 
> Opinions on which or either of them to use? If the former, I can make a pass of existing docs to convert them for consistency's sake. If the latter, I'll update this PR to only use `&#124`;

**Comment by char0n** [comment]
@tim-lai my take on this: https://github.com/swagger-api/apidom/pull/2038#issuecomment-1252055449

**Comment by tim-lai** [comment]
> IMHO it doesn't matter. Both character sequences render correctly and are used within the OpenAPI documentation interchangeably.

Great. Will leave as-is. Thanks.
