### ISSUE TITLE
ls: oas3.1 documentation for discriminator

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#2041]

**Comment by tim-lai** [comment]
@frantuma Just confirming we want the entire documentation for this object. Note that there is not an explicit "examples" section, but there is a full-length description on how to use the Discriminator Object with examples.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#discriminatorObject

**Comment by frantuma** [comment]
@tim-lai I would probably go for [field docs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-20) defined in table, appending [Composition and Inheritance section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#composition-and-inheritance-polymorphism) and possibly a "see more" link to [full discriminator object docs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#discriminator-object)

@char0n any comment/thought?

**Comment by char0n** [comment]
As discussed on slack, let's go for cherry picking, but we need to fully document which parts of the docs where cherry picked and why so that future contributor knows the pattern. As it happens, future contributor is going to be me with OpenAPI 3.0.x suport, so we'll see how it works.
