### ISSUE TITLE
OpenAPI 3.0.x - `Link.operationId` field lint rules

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#2181]
`Link.operationId` for OpenAPI 3.0.x says the following:

> The name of an existing, resolvable OAS operation, as defined with a unique operationId. This field is mutually exclusive of the operationRef field.

This technically means that any local or remote Operation Object can be referenced by `operationId`. If we limit the linting for `Link.operationId` for only local ones, it would not be what spec says we should do. 

So I currently see three ways how to proceed here:

### 1. Do no linting

This is the simplest one to implement as no implementation is required.

### 2. Do linting only on local definition Operation Objects

As I said before, this is against the spec as the spec explicitly states `existing and resolvable Operations`.

### 3. Do linting on existing, resolvable Operation Objects

That would require dereferencing and more context (env, baseURI). 

---

NOTE: when implemented, this will apply also to OpenAPI 3.1.0 spec

**Comment by frantuma** [comment]
@char0n I'd go for 1 for now, and possibly open a ticket/discussion about "dereferenced validation", which we will need sooner than later, and would cover other similar cases

**Comment by char0n** [comment]
@frantuma right, I'm for 1 as well. I'll close this issue and implement only `type` rule for `Link.operationId` without any additional logic.

Let's have a discussion around "dereferenced validation" during next week.
