### ISSUE TITLE
OAS3.1 components.pathItems should have its own lint rule

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#2310]
### Q&A (please complete the following information)
 - ApiDOM version: 0.56.2
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Describe the bug you're encountering

The linter for `components.pathItems` should reflect the lint rules for `pathItem` and override the default `component` lint rules

### To reproduce...

1. Define an OpenAPI 3.1 definition , or Go to 'Load OpenAPI 3.1 Fixture'
2. add the following snippet:
```
components:
  pathItems:
    /c:
```
3. View lint error, line 28: `components keys must match the regular expression: `^[a-zA-Z0-9\.\-_]+$``

### Expected behavior

No lint error

### Screenshots

![apidom-issue-2310](https://user-images.githubusercontent.com/12902658/204392058-fb0c9d10-1d32-4260-979e-de2c9205c844.png)

### Additional context or thoughts

Removing the slash also removes the lint error. but the lint error shouldn't be present anyways
```
components:
  pathItems:
    c:
```

**Comment by tim-lai** [comment]
Upon further review, is the linter correct, and user should define paths./c as follows:

![apidom-issue-2310-1](https://user-images.githubusercontent.com/12902658/204397346-0ba146d1-0984-4ec9-b737-7bfc40981def.png)

**Comment by char0n** [comment]
All the maps defined as `Component Object` values must follow:

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

That means that every `Path Item Object` under `Components.pathItems` should use key matching `^[a-zA-Z0-9\.\-_]+$`.

```yaml
components:
  pathItems:
    pathItem1:
       summary: testing summary
       description: testing description
paths:
  /url/path:
    $ref: "#/components/pathItems/pathItem1"
```

Closing as false positive.
