### ISSUE TITLE
Missing dependencies on apidom-ast from apidom-ns-openapi-3-1 and apidom-ns-json-schema-draft-4

### ISSUE THREAD

**Issue by tomdegoede** [swagger-api/apidom#2871]
@swagger-api/* version: 0.70.1

When bundling our application with webpack using **pnpm** for node_module resolution we encounter errors in `@swagger-api/apidom-ns-json-schema-draft-4/es/refractor/visitors/json-schema/EnumVisitor.js` and `@swagger-api/apidom-ns-openapi-3-1/es/refractor/visitors/open-api-3-1/schema/EnumVisitor.js` because these packages do not list `@swagger-api/apidom-ast` as their dependency.

pnpm creates an isolated symlink structure to make sure that npm packages only resolve their own dependencies.

**Comment by char0n** [comment]
Hi @tomdegoede,

Thanks for the report I can confirm and working on the fix.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/apidom/pull/2875. There will be new release before the end of this week.

**Comment by lizthegrey** [comment]
Any news on the release @char0n?

**Comment by char0n** [comment]
@lizthegrey ETA during today

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/apidom/releases/tag/v0.70.3

**Comment by lizthegrey** [comment]
> Released as [`v0.70.3` (release)](https://github.com/swagger-api/apidom/releases/tag/v0.70.3)

Thanks! Fix confirmed working, yarn-pnp is happy now.

**Comment by char0n** [comment]
https://www.npmjs.com/package/@swagger-api/apidom-core Doesn't show readme as well.
