### ISSUE TITLE
apidom-error: AggregateError polyfilling

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3128]
AggregateError is available since Node.js >=15. ApiDOM is used under the hood of [swagger-client](https://github.com/swagger-api/swagger-js) which must work on Node.js >=12.20.0. The goal of this issue is to provide compatibility for Node.js >= 12.20.0.

Refs https://github.com/swagger-api/swagger-js/issues/3127

**Comment by jindalshubham660** [comment]
Hi we are facing the same issue in our nodejs based app which runs on node 14.17.5, what can we do to quickly fix the issue?

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/apidom/pull/3129. @jindalshubham660 have a look if you wish to help.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/apidom/releases/tag/v0.76.1
