### ISSUE TITLE
Double encoding when sanitized URL with encoded symbols like %2F (/), %3B (;) etc. provided to sanitize() function

### ISSUE THREAD

**Issue by stepashka69** [swagger-api/apidom#3270]
### Q&A (please complete the following information)
 - ApiDOM version: 0.77.0
### Describe the bug you're encountering
The bug is follow up of the by reported for SwaggerUI https://github.com/swagger-api/swagger-ui/issues/9304 where it causes the practical problem.

Calling the `sanitize()` function in  https://github.com/swagger-api/apidom/blob/main/packages/apidom-reference/src/util/url.ts#L248 cause double encoding when URL already contains encoded 'special' symbols: `; / ? : @ & = + $ , #`

### To reproduce...

1. Call `sanitize()` function with URL that contains encoded symbols %2F , %3B etc. Similar to test case https://github.com/swagger-api/apidom/blob/main/packages/apidom-reference/test/util/url.ts#L294 . For example `sanitize('https://example.com/path%20with%20spaces%2Fslashes%3Bsemicolons/?including=in%3Fparameters')`
2. The expected output is the same URL: `'https://example.com/path%20with%20spaces%2Fslashes%3Bsemicolons/?including=in%3Fparameters`. 
The real output is this: `https://example.com/path%20with%20spaces%252Fslashes%253Bsemicolons/?including=in%253Fparameters` . 
The `%` of the `%2F` and `%3B` are encoded. It should not happen.

### Expected behavior

The encoded URL passed to `sanitize()` should remain the same for all possible combinations of encoded symbols

### Additional context or thoughts
The reason for the issue is that `decodeURI()` and `encodeURI()` leave 'special' symbols `; / ? : @ & = + $ , #` encoding unchanged. It is mentioned in the documentation at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI#description and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#description .

**Comment by char0n** [comment]
Resolved in https://github.com/swagger-api/apidom/pull/3271
