### ISSUE TITLE
OpenAPI: Swagger 2.0 basePath linting rule fails when value contains 's'

### ISSUE THREAD

**Issue by CalemRoelofsSB** [swagger-api/apidom#3565]
### Q&A (please complete the following information)
 - OS: MacOS Ventura 13.6.3
 - Browser: Firefox 
 - Version: 121.0
 - Method of installation: found while using https://editor-next.swagger.io/
 - ApiDOM version: 0.85.0
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering
The Swagger 2.0 linting rule for validating that the `basePath` is correctly formatted (https://github.com/swagger-api/apidom/edit/main/packages/apidom-ls/src/config/openapi/swagger/lint/base-path--pattern.ts) fails erroneously whenever there is a `basePath` with the character `s` in it.

### To reproduce...

1. Load up any Swagger 2.0 definition in https://editor-next.swagger.io/
2. Add `basePath: /s123` or `basePath: /123s` or `basePath: /hello/worlds` or any string starting with `/` and containing the character `s`

### Expected behavior
No validation error is displayed

### Screenshots
![image](https://github.com/swagger-api/apidom/assets/96050034/7d7d15c5-6266-42d9-a8cb-94b2ca9f35bf)
![image](https://github.com/swagger-api/apidom/assets/96050034/07ed5342-96b0-4b69-8a55-5604575a7f06)
![image](https://github.com/swagger-api/apidom/assets/96050034/359b9714-b00b-46b5-a1d9-15a15dc229cd)

### Additional context or thoughts
This appears to be caused by the regex used for this rule found [here](https://github.com/swagger-api/apidom/edit/main/packages/apidom-ls/src/config/openapi/swagger/lint/base-path--pattern.ts)

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/apidom/pull/3566
