### ISSUE TITLE
apidom-ns-asyncapi-2: redundant stamps/classes

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/apidom#3799]
Currently we have some redundant files in the AsyncAPI namespace package, which just duplicate `FallbackVisitor` ex: https://github.com/swagger-api/apidom/blob/6e1fe1c4c4cd11ed05481c8b59bfb41608fb8a1a/packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/message-example/HeadersVisitor.ts

We can remove these files and instead add a reference to `FallbackVisitor` in `specification`, ex: `headers: { $ref: '#/visitors/value' }`

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/apidom/pull/3804
