### ISSUE TITLE
Bump tree-sitter and grammars to >= 0.21.0

### ISSUE THREAD

**Issue by jpulec** [swagger-api/apidom#4048]
### Is your feature request related to a problem?
The newer versions of tree-sitter and its grammars use `prebuildify` which means that you don't need to run postinstall scripts to get the necessary built bindings. This makes things much nicer for any projects that are downstream.

### Describe the solution you'd like
Bump to later versions of tree-sitter and its grammars.

### Describe alternatives you've considered
N/A

**Comment by char0n** [comment]
Hi @jpulec,

Unfortunately we cannot at this point. The reasoning is in https://github.com/swagger-api/apidom/issues/194#issuecomment-1602399929. Long story short the `tree-sitter-yaml` grammar is abandoned and tree-sitter team is working on new one, which is going to be utilized in https://github.com/swagger-api/apidom/issues/4033. The latest tree-sitter tool-chain will be utilized in ApiDOM in near (foreseeable) future
