### ISSUE TITLE
Complete External Resolution for AsyncApi 2.3.0

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#428]
We already have external resolution implementation for Reference Objects. Support for Schema Object needs to be added. Additional usecases that are not covered in current implementation needs to be implemented and new tests covering various usecases must be introduced.

- [x] [add support for ChannelItem external resolution](https://github.com/swagger-api/apidom/issues/559)
- [x] tests

**Comment by ponelat** [comment]
Completion: Add missing tests and any bug fixes in this area.
