### ISSUE TITLE
Uncaught (in promise) : Hover operation canceled

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#455]
steps to reproduce:
1. use petstore3 definition
2. Change the `openapi` version from `3.0.2` to `3.1.2`.
3. Note the red squiggly indicating error
4. Hover over red squiggly
5. refer to console error in screenshot

![Screen Shot 2021-06-25 at 11 11 22 AM](https://user-images.githubusercontent.com/12902658/123482826-a7284680-d5ba-11eb-9bfb-540725614f6a.png)

**Comment by ponelat** [comment]
@tim-lai @frantuma if/when possible please try reproduce this issue and fix. If not, I'd like to close out this ticket.

**Comment by tim-lai** [comment]
Appears resolved. closing issue
 
[x] load petstore3 json definition from url. comments: IDE auto convert to yaml. follow steps to change version does not produce console errors
[x] load default oas3.0 json from editor menu. comments: follow steps to change version does not produce console error
